workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.bmtpc.iosapp

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..

      - name: Apply iOS signing
        script: |
          xcode-project use-profiles

      - name: Build iOS
        script: |
          xcodebuild \
            -workspace ios/TestApp.xcworkspace \
            -scheme TestApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/TestApp.xcarchive archive

    artifacts:
      - $CM_BUILD_DIR/**/*.ipa